# Generated by Django 4.1.2 on 2022-10-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_geeksmodelimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModelValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_field', models.IntegerField()),
            ],
        ),
    ]
